### ISSUE TITLE
conda recipe does not include Windows patch, shell script missing copy

### ISSUE THREAD

**Issue by jabooth** [menpo/cyrasterize#4]
the travis-focused conda recipes at `./conda` are missing a windows patch that is present on the version on [conda-recipes](https://github.com/menpo/conda-recipes/tree/master/cyrasterize). This is because we no longer need the `source` key in the `meta.yaml` (we just manually copy the dir as suggested in the conda docs [here](http://conda.pydata.org/docs/build.html):

> ```python
# Note, the source section is optional. If you want to specify a source
# location locally, the easiest way is to not specify the source here, but
# to just add something like
#
# cp -r $RECIPE_DIR/../src .
# cd src
# ...
#
# in build.sh (and similarly in bld.bat). This assumes the source is
# shipped alongside the recipe in src.
```

This should be rectified before we add app veyor support.

**Comment by patricksnape** [comment]
I don't believe this is necessary any longer?
