### ISSUE TITLE
Lost Python 3 support

### ISSUE THREAD

**Issue by patricksnape** [menpo/cyrasterize#8]
Currently, loading the shaders causes a string vs bytes buffer issue between Python 2 and 3. Really would like Python 3 support!

However, my ugly fix seemed to suggest that all the tests were failing on Python 3?

**Comment by jabooth** [comment]
Fixed in https://github.com/menpo/cyrasterize/commit/abb89a4e0debd5c36b1f77e7080e3a3421acece6
